// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using Common;
using System.Collections.Generic;

public class MyTools
{ 

	MyTools(){}

	public class ActionMethod
	{
		private ArrayList mMethodList = new ArrayList();

		public void Add(System.Action methName)
		{
			mMethodList.Add(methName);
		}

		public void Run()
		{
			for (int i=0;i<mMethodList.Count;i++)
				((System.Action)mMethodList[i])();
		}

	}

	public struct DelegateEvent<T>
	{
		public delegate void _delegateEvent<T>(T item);
		
		_delegateEvent<T> func;
		T param;
		
		public void Run()
		{	
			if (func!= null)
				func(param);
		}
		
		public DelegateEvent(_delegateEvent<T> _func,T _param)
		{
			func  = _func;
			param = _param;
		}
	}

}


