// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using Common;
using System.Collections.Generic;

public class ShipModule
{ 
	private GameObject 	 m_model;
	private ArrayList 	 m_modelFireSlots = new ArrayList();
	
	public ShipModule (GameObject obj)
	{
		SetModel(obj);
	}

	public void SetModel(GameObject obj)
	{
		m_model = obj;

		GameObject fireSlot1 = obj.GetChildrenWithName("FirePlace1");
		GameObject fireSlot2 = obj.GetChildrenWithName("FirePlace2");

		if (fireSlot1)
			m_modelFireSlots.Add(fireSlot1);

		if (fireSlot2)
			m_modelFireSlots.Add(fireSlot2);
	}

	public ArrayList  GetFireSlots() { return m_modelFireSlots; }
	public GameObject GetModel()	 { return m_model; }

	public GameObject GetFireSlot(Vector3 target)
	{
		GameObject findSlot = null;
		float bestDist;

		Debug.Log("GetFireSlot "+m_modelFireSlots.Count);

		if (m_modelFireSlots.Count >= 0)
		{
			if (m_modelFireSlots.Count == 0)
				return null;
			else if (m_modelFireSlots.Count == 1)
				return (GameObject)m_modelFireSlots[0];
		}
        
		findSlot = (GameObject)m_modelFireSlots[0];
		bestDist = Vector3.Distance(target, (findSlot).transform.position);

		for (int i=1;i<m_modelFireSlots.Count;i++)
		{
			Vector3 pos1 = ((GameObject)m_modelFireSlots[i]).transform.position;
			float curLen  = Vector3.Distance(target, pos1);

			if (curLen <= bestDist)
			{
				findSlot = (GameObject)m_modelFireSlots[i];
				bestDist = curLen;
			}

		}
		return findSlot;
	}
}


