//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UIC
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPlayerInfo 
	{
		object MaxHP { get;set; }

		object MaxEnegry { get;set; }

		object MaxEXP { get;set; }

		object Position { get;set; }

		object Name { get;set; }

		object Speed { get;set; }

		object CurentEnergy { get;set; }

		object CurentExp { get;set; }

		object CurentHP { get;set; }

	}
}

