//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UIC
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPlayerInfo 
	{
		int MaxHP { get;set; }

		int MaxEnegry { get;set; }

		int MaxEXP { get;set; }

		int Position { get;set; }

		int Name { get;set; }

		int Speed { get;set; }

		int CurentEnergy { get;set; }

		int CurentExp { get;set; }

		int CurentHP { get;set; }

	}
}

